/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./node_modules/@custom/components/button/src/button.vue')['default']
    CtButton: typeof import('@custom/components')['Button']
    CtForm: typeof import('@custom/components')['Form']
    CtFormItem: typeof import('@custom/components')['FormItem']
    CtInput: typeof import('@custom/components')['Input']
    Form: typeof import('./node_modules/@custom/components/form/src/form.vue')['default']
    FormItem: typeof import('./node_modules/@custom/components/formItem/src/formItem.vue')['default']
    Input: typeof import('./node_modules/@custom/components/input/src/input.vue')['default']
  }
}
